<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry?</p>
<form action="">
<div class="options">
                            <div>
                                    <span><input type="radio" name="option1"  ></span>
                                </span>
                                <span>Options A</span>
                            </div>
                            <div>
                                    <span><input type="radio" name="option1" ></span>
                                </span>
                                <span>Options B</span>
                            </div>
                            <div>
                                    <span><input type="radio" name="option1"  ></span>
                                </span>
                                <span>Options C</span>
                            </div>
                            <div>
                                    <span><input type="radio" name="option1"  ></span>
                                </span>
                                <span>Options D</span>
                            </div>
                        </div>
                        <div style="padding: 20px;">
                <button style="padding: 10px;" type="submit">SUBMIT QUIZ</button>
            </div>
</form>